// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrItq98zU0eDZRkOHjr8bmRqs8zHE1fM0',
    appId: '1:267244592062:web:9980711bfb61e49bc777ef',
    messagingSenderId: '267244592062',
    projectId: 'e-book-fee3a',
    authDomain: 'e-book-fee3a.firebaseapp.com',
    storageBucket: 'e-book-fee3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYNjcWfkOvFUS-MMCnGm9yLlaRi5riOc',
    appId: '1:267244592062:android:adacbbbced53bc73c777ef',
    messagingSenderId: '267244592062',
    projectId: 'e-book-fee3a',
    storageBucket: 'e-book-fee3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhAbRpaeWXdBlAbBnqCdmNeqkKjs1dJfQ',
    appId: '1:267244592062:ios:cbb21b661b385d59c777ef',
    messagingSenderId: '267244592062',
    projectId: 'e-book-fee3a',
    storageBucket: 'e-book-fee3a.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhAbRpaeWXdBlAbBnqCdmNeqkKjs1dJfQ',
    appId: '1:267244592062:ios:cbb21b661b385d59c777ef',
    messagingSenderId: '267244592062',
    projectId: 'e-book-fee3a',
    storageBucket: 'e-book-fee3a.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrItq98zU0eDZRkOHjr8bmRqs8zHE1fM0',
    appId: '1:267244592062:web:b79040e77f619a8bc777ef',
    messagingSenderId: '267244592062',
    projectId: 'e-book-fee3a',
    authDomain: 'e-book-fee3a.firebaseapp.com',
    storageBucket: 'e-book-fee3a.appspot.com',
  );

}